// Auto-generated by galaxy-design CLI - DO NOT EDIT MANUALLY
// This file is regenerated every time you add or remove components

// Component exports
export * from './accordion';
export * from './alert';
export * from './alert-dialog';
export * from './area-chart';
export * from './aspect-ratio';
export * from './authentication';
export * from './avatar';
export * from './badge';
export * from './bar-chart';
export * from './breadcrumb';
export * from './button';
export * from './calendar';
export * from './calendar-range';
export * from './card';
export * from './chat-ui';
export * from './checkbox';
export * from './collapsible';
export * from './command';
export * from './context-menu';
export * from './dialog';
export * from './donut-chart';
export * from './dropdown-menu';
// export * from './email'; // Placeholder - not yet implemented
export * from './empty';
// export * from './featured'; // Placeholder - not yet implemented
export * from './form';
export * from './gauge-chart';
export * from './hover-card';
export * from './input';
export * from './kbd';
export * from './label';
export * from './line-chart';
export * from './menubar';
export * from './mixed-chart';
export * from './navigation-menu';
export * from './pagination';
export * from './pie-chart';
export * from './popover';
export * from './progress';
export * from './radar-chart';
export * from './radio-group';
export * from './resizable';
export * from './scatter-chart';
export * from './scroll-area';
export * from './select';
export * from './separator';
export * from './sheet';
export * from './sidebar';
export * from './skeleton';
export * from './slider';
export * from './switch';
export * from './table';
export * from './tabs';
export * from './tags-input';
export * from './textarea';
export * from './toast';
export * from './toggle';
export * from './toggle-group';
export * from './toolbar';
export * from './tooltip';
export * from './typography';

// Provider imports for components that require Angular providers
import { provideRdxDialogConfig } from '@radix-ng/primitives/dialog';
import { provideRdxTooltipConfig } from '@radix-ng/primitives/tooltip2';

/**
 * Provide all required Angular providers for Galaxy UI components
 * Add this to your app.config.ts providers array:
 * 
 * ```typescript
 * export const appConfig: ApplicationConfig = {
 *   providers: [
 *     provideGalaxyComponents(),
 *     // ... other providers
 *   ]
 * };
 * ```
 * 
 * This function provides configuration for: Dialog, Tooltip
 */
export function provideGalaxyComponents() {
  return [
    provideRdxDialogConfig(),
    provideRdxTooltipConfig({}),
  ];
}
